### ISSUE TITLE
Specificity is miscalculated for nested selectors

### ISSUE THREAD

**Issue by C-Ezra-M** [mrmlnc/vscode-scss#161]
- VS Code Version: 1.70.2
- SCSS IntelliSense Version: v0.10.0
- Operating System: Windows 11 Version 21H2 Build 22000.856

Reproducible Case:

This SCSS code snippet.
```scss
.toc {
  #left-col & {
    @media screen and (min-width: 960px) {
      display: none;
    }
  }
}
```

Steps to Reproduce:

1. Copy-paste the above code snippet.
2. Hover over `#left-col &`.

Expected: The specificity is calculated as `(1, 1, 0)`.
Actual: The specificity is calculated as `(1, 0, 0)`, ignoring the `toc` class's specificity.
