### ISSUE TITLE
Feature: preview variable colors which represent rgba (3 numbers)

### ISSUE THREAD

**Issue by gianpaj** [mrmlnc/vscode-scss#170]
```css
  --ctm_merchandise-001: 0, 199, 101;
  --ctm_secondary-800: 239, 143, 15;
  --ctm_secondary-main: 241, 201, 51;
```

later we use them like this
```css
.ctm_c-merchandise-001 {
  --text-opacity: 1;
  color: rgba(var(--ctm_merchandise-001), var(--text-opacity));
}

.ctm_bg-merchandise-001,
.h\:ctm_bg-merchandise-001:hover {
  background-color: rgba(var(--ctm_merchandise-001));
}
```

that's why the variables do not have `rgba()` inside
