### ISSUE TITLE
scss variables aren't recognized in `@media()` for definition and hover providers

### ISSUE THREAD

**Issue by mbehzad** [mrmlnc/vscode-scss#175]
- VS Code Version: 1.95.1
- SCSS IntelliSense Version: 0.10.0
- Operating System: Windows 11

Reproducible Case:

```scss
$desktop: min-width 1200px;

@media ($desktop) {}
```

Steps to Reproduce:

1. hover on `$desktop` in the media query.
2. no hover info / ctrl+click won't bring you to where the variable is defined.

I'll provide a pull request for the fix.
