### ISSUE TITLE
SCSS IntelliSense  Exception

### ISSUE THREAD

**Issue by hua03** [mrmlnc/vscode-scss#67]
## Q1:
I only declare a variable, but it shows three tips.
![image](https://user-images.githubusercontent.com/19561959/37263500-7619f8ac-25e3-11e8-9b6e-256e7471cb7d.png)

## Q2:

This extension sometimes fails and the console reports this error **TypeError: Cannot read property 'getTime' of undefined**

![image](https://user-images.githubusercontent.com/19561959/37263737-73a71aa4-25e4-11e8-91de-cbbfdcf22328.png)

**Comment by taylorsolomon** [comment]
Getting the same thing.

**Comment by AlexandruDinulescu** [comment]
I have the same issue as Q1. Can we have a developer input on this?

**Comment by morgzz** [comment]
I'm running into this error as well.
```
[Error - 12:17:03 PM] (node:43360) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 55): TypeError: Cannot read property 'getTime' of undefined
```

**Comment by avilde** [comment]
Same issue.
When I renamed my file includes with underscore prefix for shorter import paths the suggestions don't work anymore and the output console logs regularly errors about cannot find file.

My variables are located in **src\styles** directory. 
The `npm run build` works fine. 
I use `.env` file with setting:
`SASS_PATH=./node_modules;./src/styles/`
Documentation:
https://create-react-app.dev/docs/adding-a-sass-stylesheet

For example:
styles/_fonts.scss variables file
```scss
$default-font-stack: "open_sans";
$font-dir: "/fonts/";
$default-font-size: 18px;
```
module file for CRA:
fonts.module.scss:
```scss
@import "fonts";

@font-face {
  font-family: $default-font-stack;
  src: url("#{$font-dir}open-sans-v16-latin-ext_latin-700-webfont.woff2") format("woff2"),
    url("#{$font-dir}open-sans-v16-latin-ext_latin-700-webfont.woff") format("woff");
  font-weight: bold;
  font-style: normal;
}
```

Ctrl + Click doesn't do anything:
![image](https://user-images.githubusercontent.com/364880/64940547-e6b1f280-d86c-11e9-8b8f-acf25e37ae1c.png)

No suggestions:
![image](https://user-images.githubusercontent.com/364880/64940608-0c3efc00-d86d-11e9-9f1e-7dd1b2f69d5e.png)

Errors in OUTPUT console regarding SCSS Intellinse not finding files:
```
[Error - 09:12:14] (node:22520) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '\src\fonts.scss'
```
