### ISSUE TITLE
Incorrect implicitly label for partial files

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#99]
- VS Code Version: 1.40.2
- SCSS IntelliSense Version: 0.8.1+
- Operating System: Windows

Reproducible Case:

```scss
// _provider.scss
@mixin gradient-striped($color: rgba(255, 255, 255, .15), $angle: 45deg) {
  background-image: -webkit-linear-gradient($angle, $color 25%, transparent 25%, transparent 50%, $color 50%, $color 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient($angle, $color 25%, transparent 25%, transparent 50%, $color 50%, $color 75%, transparent 75%, transparent);
  background-image: linear-gradient($angle, $color 25%, transparent 25%, transparent 50%, $color 50%, $color 75%, transparent 75%, transparent);
}

.test1 {
  @include gradient-striped;
  background-size: 40px 40px;
}

// test.scss
@use "provider" as p;

.test2 {
  @include p.gradient-striped;
  background-size: 40px 40px;
}
```

Steps to Reproduce:

1. Open the `test.scss` file;
2. Hover the `gradient-striped` node; The lettering would be `@import "_provider.scss";`; Go to the definition;
3. Save the `_provider.scss` file;
4. Back to the `test.scss` file
5. Hover the `gradient-striped` node; The lettering would be `@import "_provider.scss"; (implicitly)`;
